eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
spring:
 application:
    name: newz-nexflix-zuul-api-gateway
server:
  port: 8091
  
#zuul:
#  routes:
#    AuthenticationService:
#      service-id: AuthenticationService
#    NewsService:
#      service-id: News-Service
#    NewsSourceService:
#      service-id: NewsSource-Service
#    UserProfileService:
#      service-id: UserProfile-Service
zuul:
  routes:
    AuthenticationService:
      url: http://localhost:8082/
    NewsService:  
      url: http://localhost:8081/
    NewsSourceService:
      url: http://localhost:8083/
    UserProfileService:
      url: http://localhost:8084/

