#spring:
# data:
#   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
#server:
# port: 8084

spring:
 application:
    name: UserProfile-Service
 data:
   mongodb:
     database: UserProfileServiceDB
     port: 27017
     host: localhost
server:
 port: 8084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka