#spring:
# data:
#   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
#server:
# port: 8083
spring:
 application:
    name: NewsSource-Service
 data:
   mongodb:
     database: NewsSourceServiceDB
     port: 27017
     host: localhost
server:
 port: 8083
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka